### ISSUE TITLE
Issues with the pom.xml file

### ISSUE THREAD

**Issue by nguyen1998pr** [vts-contributor/vts-kit-ms-template#1]
Hi, I'm newbie to Java and i am looking for fast development with this Java Kit, when i open this project for the first time i get below problems. So what should i do to resolve all, thanks.
![image](https://user-images.githubusercontent.com/55442292/167384274-25acad2e-8fcb-4c40-97f3-91ede2a57886.png)

**Comment by viettel-solutions** [comment]
Hi @nguyen1998pr ,
- Please refer to the [Quick Start](https://github.com/vts-contributor/vts-kit-ms-template#quick-start) to generate your project using our toolkit.
- Unless you want to start a contribution, you should check out [Maven Archetype](https://maven.apache.org/guides/introduction/introduction-to-archetypes.html) introduction.

Thanks

**Comment by nguyen1998pr** [comment]
Thanks for your reply, I figured out the cause of the problem was the proxy, pointed out at https://maven.apache.org/guides/mini/guide-proxies.html.

But it throws another error when I'm following the Quick Start and using the command:
`mvn archetype:generate -DarchetypeGroupId=com.atviettelsolutions -DarchetypeArtifactId=vts-kit-ms-template -DarchetypeVersion=1.0.1`

The error is described below:
![image](https://user-images.githubusercontent.com/55442292/167811217-fd13c7ac-37a9-40d8-882a-6ce09fe57d6c.png)

**Comment by viettel-solutions** [comment]
Hi @nguyen1998pr 
While waiting for version 1.0.1 to be synced by maven. Temporarily you use version 1.0.0 with the command below.
```shell
mvn archetype:generate -DarchetypeGroupId=com.atviettelsolutions -DarchetypeArtifactId=vts-kit-ms-template -DarchetypeVersion=1.0.0
```
Thanks

**Comment by nguyen1998pr** [comment]
The error has been resolved after updating to the new version, thanks a lot!
